/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* for loop 


In its most common form, the initialization portion of the loop sets a loop control variable
to an initial value. The condition is a Boolean expression that tests the loop control variable. 
If the outcome of that test is true, the for loop continues to iterate. 
If it is false, the loop terminates. The iteration expression determines 
how the loop control variable is changed each time the loop iterates. 
Here is a short program that illustrates the for loop:

/*
  Demonstrate the for loop.
  Call this file ForDemo.java.
*/

/*class ForDemo {
  public static void main(String args[]) {
int count;
    for(count = 0; count < 5; count = count+1)
      System.out.println("This is count: " + count);
    System.out.println("Done!");
  }
This loop iterates five times.

The output generated by the program is shown here:
   This is count: 0
   This is count: 1
   This is count: 2
   This is count: 3
   This is count: 4
   Done!
    }
*/


package GalToLit;

/**
 *
 * @author srijana
 */
public class java {
    
     public static void main(String args[]) {
         //Try This 1-2
      //GalToLitTable.java
   double gallons, liters;// gallons ,litres  is a variable of type double 
int counter; // counter is a varibale of type of int


 counter = 0;//Line counter is initially set to zero.
 
 
 //for(initialization; condition; iteration) statement;

for(gallons = 1; gallons <= 100; gallons++) {
  liters = gallons * 3.7854; // convert to liters
  System.out.println(gallons + " gallons is " +
                            liters + " liters.");
         counter++;//Increment the line counter with each loop iteration.
         
         // every 10th line, print a blank line
         if(counter == 10) {       // If counter is 10, output a blank line.
           System.out.println(); //
           counter = 0; // reset the line counter
         }
} }
}

//